### ISSUE TITLE
Missing any form of feedback

### ISSUE THREAD

**Issue by prestonzen** [SoHeil-R/google-traffic-bot#1]
![image](https://github.com/user-attachments/assets/1dbcaff4-b051-47f6-86ef-2a41696ebf24)

Not even sure of what's happening

**Comment by prestonzen** [comment]
Fixed the bugs in proxy.js

Can merge if this is active again

https://github.com/prestonzen/google-traffic-bot

**Comment by SoHeil-R** [comment]
Thanks, it's merged!
